### ISSUE TITLE
데이터베이스 구조 관련

### ISSUE THREAD

**Issue by Edwins247** [PolyCoders365/Just-Turn-On-Timer#5]

**Comment by dev210202** [comment]
### 배경
우리 프로젝트는 Folder - Folder, Document(Todo, Schedule) 방식의 중첩구조를 사용함.
- 이 구조로 Firebase Realtime DB에 바로 setValue를 하고 read를 해서 Folder 객체로 변환 시 Folder의 하위 Folder의 타입을 Any로 설정해야 받아올 수 있음.
- 이때 Any로 받아온 데이터들을 타입에 맞게 다시 변환을 해야 정상적으로 사용할 수 있음

#### 여기서 든 의문점
우리가 애초에 Realtime DB에 올라가는 구조를 변경하는게 더 효율적으로 사용할 수 있지 않을까?
그래서 데이터를 효율적으로 사용할 수 있는 방식에 대해서 찾게됨
##### 1. Realtime DB에 setValue를 할때 key값을 변경하여 읽을 때 필터링해서 변환하는 방식 
##### 2. Folder 값을 Realtime DB에 올릴 때 Folder, Document들 끼리의 연관관계를 짓고 평면화 시키는 방식
##### 3. FireStore를 사용해서 문서 컬렉션 방식으로 변경

**Realtime Database를 사용하는 이유가 간단한 조회 및 데이터 구조를 사용해서 였는데 지금의 구조는 FireStore가 더 장점이 많은 것으로 생각되어서 FireStore로 변경하고, 문서 컬렉션 방식으로 변경하는 것으로 결정.** 

FireStore vs Realtime DB
|  | FireStore | Realtime DB |
| ---- | ---- | ---- |
| 정보 | 쿼리 가능성, 확장성, 고가용성이 필요한 리치 데이터 모델을 사용하는 애플리케이션에 적합, 지연시간이 짧은 클라이언트 동기화 및 오프라인 데이터 액세스 제공 | 간단한 조회, 확장성이 제한적, 지연시간이 짧은 동기화가 필요한 단순한 데이터 모델을 사용하는 애플리케이션에 적합 |
| 데이터 모델 | 데이터를 문서 컬렉션으로 저장<br>문서에 있는 하위 컬렉션을 사용하여 복잡한 계층적 데이터를 대규모로 쉽게 정리<br>비정규화 및 데이터 평면화가 덜 필요 | 데이터를 하나의 큰 Json 트리로 저장<br>복잡한 계층적 데이터를 대규모로 정리하기가 보다 어려움 |
| 실시간 및 오프라인 지원 | AOS, IOS, Web | AOS, IOS |
| 접속 상태 | 지원 X, Cloud Funtions를 사용해서 Realtime DB와 동기화로 사용 가능 | 지원 O |
| 쿼리 | 복합 정렬 및 필터링 기능을 갖춘 색인화된 쿼리 | 제한적인 정렬 및 필터링 기능을 갖춘 깊은 쿼리 |
| 쓰기 및 트랜잭션 | 고급 쓰기 및 트랜잭션 작업 | 기본 쓰기 및 트랜잭션 작업 |
| 안전성 및 성능 | 자동으로 확장되는 리전 내 및 멀티 리전 솔루션<br>- 응답 시간이 30밀리초 이하로 지연시간이 짧은 솔루션 | 리전 솔루션<br>- 지연시간이 매우 짧으며 일반적으로 10밀리초 이하, 동기화가 자주 발생할때 적합 |

**Comment by Edwins247** [comment]
### 기본 구조 및 생각한 DB 구조
![image](https://github.com/PolyCoders365/Just-Turn-On-Timer/assets/144297891/0766bfac-4780-4411-a790-4b68d471802b)
- 중첩구조가 기본이기 때문에 생성 -> 생성 -> 생성할 경우 Collection & Document를 반복적으로 추가할 수 있게 하고 이에 대해선 일반 필드값을 추가한 Collection에 필드값으로 추가하면 되지만 List의 경우 객체가 들어있고 구분을 할 수가 있는데 이 역시도 List 자체를 Document로써 생성을 하는 방향으로 진행할 예정

![image](https://github.com/PolyCoders365/Just-Turn-On-Timer/assets/144297891/e4e54a3e-83a5-4f41-b241-61c824d2894f)
![image](https://github.com/PolyCoders365/Just-Turn-On-Timer/assets/144297891/3d943e27-a6ff-4e4a-b4fd-0ad9c0181040)
- Firestore를 사용하기 위해 기본 데이터 클래스 구조도 Todo 기준으로 위와 같이 변경이 될 것임 Code 부분처럼 받은 값에 대해서 입력받고 2번째 사진과 같이 입력받고 데이터가 추가되어 Document & Field 값 추가가 됨

**Comment by Edwins247** [comment]
### Create 구현 스니펫
- 본 설명과 코드는 확정 코드는 아님, 변경이 있을 수 있지만 앞서 논의한 Firestore 구조대로 만든 것을 반영함
- 그리고 Todo를 메인으로 잡았기 때문에 Folder 생성 및 이외 로직은 View에 맞춰서 수정될 수 있음

1. Folder 객체 내 title & docs 필드에 대해서 컬렉션 생성 후 title은 필드로 추가, docs의 경우 순서대로 인덱스로 Document 생성함
```kotlin
fun saveFolderToFirestore(folder: Folder) {
    val db = FirebaseFirestore.getInstance()

    // Create a new collection with the title of the folder
    val collectionRef = db.collection(folder.title)

    // For each doc in the folder, create a new document in the collection
    folder.docs.forEachIndexed { index, doc ->
        // Use the index as the document ID
        val docRef = collectionRef.document(index.toString())

        // Set the document data
        docRef.set(doc)
    }
}
```

2. Folder 컬렉션 생성 후 docs를 Document로 생성, 그리고 그 docs에 순서대로 생성된 Document 내의 Todo, Content, Ref에 대한 객체를 각각 필드값과 서브 컬렉션 생성 후 서브 컬렉션 내 Document로 생성해서 각 Content, Ref 값을 저장함
```kotlin
fun addTodoToFolderDocument(folder: Folder, index: Int, todo: Todo) {
    val db = FirebaseFirestore.getInstance()

    // Get a reference to the document at the specified index
    val docRef = db.collection(folder.title).document(index.toString())

    // Set the Todo fields
    val todoData = hashMapOf(
        "title" to todo.title,
        "date" to todo.date,
        "time" to todo.time,
        "tag" to todo.tag
    )
    docRef.set(todoData)

    // Create a subcollection for the todos
    val todosCollectionRef = docRef.collection("todos")

    // For each todo in the list, create a new document in the subcollection
    todo.todos.forEachIndexed { todoIndex, todoItem ->
        // Use the index as the document ID
        val todoDocRef = todosCollectionRef.document(todoIndex.toString())

        // Check the type of the todoItem and set the document data accordingly
        when (todoItem) {
            is Content -> todoDocRef.set(hashMapOf("content" to todoItem.content))
            is Ref -> todoDocRef.set(hashMapOf("ref" to todoItem.ref))
        }
    }
}
```

3. Ref의 경우, 입력시 그 이름을 가지는 Document를 찾아서 해당 Reference를 Ref의 string 값으로 저장해서 Firestore에 저장을 하게끔 해야하는데 그럴려면 검색시 Ref를 찾는 별도의 read 함수를 만듬
- 단, Firestore에선 NoSQL DB이기 때문에 컬렉션을 지정하지 않고 전체 데이터베이스 탐색에 성능 이슈와 전체 데이터베이스 기능을 제공하지 않는다고 해서 컬렉션을 특정 지어서 그 컬렉션 내 Document의 검색 및 순회를 해야한다고 함
- 그렇게 해서 ref를 찾아서 set을 해야할 것임
```kotlin
suspend fun getDocumentReferenceByFieldValue(collection: String, value: String): DocumentReference? {
    val db = FirebaseFirestore.getInstance()

    // Query the collection for documents where any field equals the value
    val querySnapshot = db.collection(collection)
        .whereEqualTo("content", value) // Assuming 'content' is a common field
        .get()
        .await()

    // If a document was found, return its reference
    if (!querySnapshot.isEmpty) {
        return querySnapshot.documents[0].reference
    }

    // If no document was found, return null
    return null
}
```
```kotlin
// 전체 순회 가정
suspend fun getDocumentReferenceByFieldValue(value: String, collections: List<String>): DocumentReference? {
    val db = FirebaseFirestore.getInstance()

    // Iterate over the known collections
    for (collection in collections) {
        // Query the collection for documents where any field equals the value
        val querySnapshot = db.collection(collection)
            .whereEqualTo("content", value) // Assuming 'content' is a common field across collections
            .get()
            .await()

        // If a document was found, return its reference
        if (!querySnapshot.isEmpty) {
            return querySnapshot.documents[0].reference
        }
    }

    // If no document was found in any collection, return null
    return null
}
```

**Comment by Edwins247** [comment]
### Read 구현 스니펫
- Read는 결국 collection을 기반으로 ref를 찾아서 `get()` 함수를 써서 document와 collection을 불러오는 방식으로 생각할 수 있음
- Create 한 방식과 경로를 잘 따져보면 될 듯 싶음
```kotlin
suspend fun getTodoFromFolderDocument(folder: Folder, index: Int): Todo? {
    val db = FirebaseFirestore.getInstance()

    // Get a reference to the document at the specified index
    val docRef = db.collection(folder.title).document(index.toString())

    // Get the document
    val doc = docRef.get().await()

    // If the document exists, convert it to a Todo object and return it
    if (doc.exists()) {
        val title = doc.getString("title") ?: ""
        val date = doc.getString("date") ?: ""
        val time = doc.getString("time") ?: ""
        val tag = doc.getString("tag") ?: ""
        val todos = doc.get("todos") as List<Any>
        return Todo(title, date, time, tag, todos)
    }

    // If the document does not exist, return null
    return null
}

suspend fun getContentFromTodoDocument(folder: Folder, docIndex: Int, todoIndex: Int): Content? {
    val db = FirebaseFirestore.getInstance()

    // Get a reference to the todo document at the specified index
    val todoDocRef = db.collection(folder.title).document(docIndex.toString()).collection("todos").document(todoIndex.toString())

    // Get the document
    val doc = todoDocRef.get().await()

    // If the document exists and is a Content, convert it to a Content object and return it
    if (doc.exists() && doc.contains("content")) {
        val content = doc.getString("content") ?: ""
        return Content(content)
    }

    // If the document does not exist or is not a Content, return null
    return null
}

suspend fun getRefFromTodoDocument(folder: Folder, docIndex: Int, todoIndex: Int): Ref? {
    val db = FirebaseFirestore.getInstance()

    // Get a reference to the todo document at the specified index
    val todoDocRef = db.collection(folder.title).document(docIndex.toString()).collection("todos").document(todoIndex.toString())

    // Get the document
    val doc = todoDocRef.get().await()

    // If the document exists and is a Ref, convert it to a Ref object and return it
    if (doc.exists() && doc.contains("ref")) {
        val ref = doc.getString("ref") ?: ""
        return Ref(ref)
    }

    // If the document does not exist or is not a Ref, return null
    return null
}
```
